[book]
authors = ["Jim Pick"]
language = "en"
multilingual = false
src = "docs"
title = "Lotus JS Client"

[output.html]
git-repository-url = "https://github.com/filecoin-shipyard/js-lotus-client"
site-url = "/js-lotus-client/"
